// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DarkModeController from "./dark_mode_controller"
application.register("dark-mode", DarkModeController)

import DatatablesController from "./datatables_controller"
application.register("datatables", DatatablesController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NestedFormController from "./nested_form_controller"
application.register("nested-form", NestedFormController)

import PromotionsController from "./promotions_controller"
application.register("promotions", PromotionsController)

import QuickProductController from "./quick_product_controller"
application.register("quick-product", QuickProductController)

import RealtimeLogsController from "./realtime_logs_controller"
application.register("realtime-logs", RealtimeLogsController)

import TerminalStatsController from "./terminal_stats_controller"
application.register("terminal-stats", TerminalStatsController)
